export const CHANGE_STATUS = "CHANGE_STATUS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUALITY = "INCREASE_QUALITY";
export const DECREASE_QUALITY = "DECREASE_QUALITY";
